//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGruppF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_freelancer
    {
        public int customer_freelancer_id { get; set; }
        public int customer_id { get; set; }
        public int freelancer_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual freelancer freelancer { get; set; }
    }
}
