//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGruppF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class education_cv
    {
        public int cv_education_id { get; set; }
        public Nullable<int> education_id { get; set; }
        public Nullable<int> cv_id { get; set; }
    
        public virtual cv cv { get; set; }
        public virtual education education { get; set; }
    }
}
