//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGruppF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class freelancer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public freelancer()
        {
            this.customer = new HashSet<customer>();
        }
    
        public int freelancer_id { get; set; }
        [Required(ErrorMessage =" oops, seems like you forgott to type your name. ")]
        public string firstname { get; set; }
        [Required(ErrorMessage = " oops, seems like you forgott to type your lastname. ")]

        public string lastname { get; set; }
        [Required(ErrorMessage = " oops, seems like you forgott to type your adress. ")]

        public string adress { get; set; }
        [Required(ErrorMessage = " oops, seems like you forgott to type your email. ")]

        public string email { get; set; }
        public Nullable<int> cv_id { get; set; }
        [Required(ErrorMessage = " oops, seems like you forgott to type your phone number.")]
        [DataType(DataType.Password)]
        public Nullable<int> phonenumber { get; set; }
        //[Compare("phonenumber")]
        //[Required(ErrorMessage = " oops, seems like you forgott to type your phone number. ")]
        //public int Confirmphonenumber { get; set; }

        public virtual cv cv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customer { get; set; }
    }
}
