//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGruppF.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class language
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public language()
        {
            this.language_cv = new HashSet<language_cv>();
        }
    
        public int language_id { get; set; }
        public string name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<language_cv> language_cv { get; set; }

        public cv Cv { get; set; }
        public IEnumerable<SelectListItem> AllLanguages { get; set; }

        private List<int> listOflanguages;
        //public List<int> ListOfLanguages
        //{
        //    get
        //    {
        //        if (ListOfLanguages == null)
        //        //{ ListOfLanguages = Cv.language.Select(m => m.Id).ToList(); }
        //        return ListOfLanguages;
        //    }
        //    set { ListOfLanguages = value; }
        //}
    }
}
