//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGruppF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektGruppFEntities : DbContext
    {
        public ProjektGruppFEntities()
            : base("name=ProjektGruppFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<cv> cv { get; set; }
        public virtual DbSet<education> education { get; set; }
        public virtual DbSet<expertise> expertise { get; set; }
        public virtual DbSet<freelancer> freelancer { get; set; }
        public virtual DbSet<language> language { get; set; }
        public virtual DbSet<Main_abilities> Main_abilities { get; set; }
        public virtual DbSet<rank_expertise> rank_expertise { get; set; }
        public virtual DbSet<skill> skill { get; set; }
        public virtual DbSet<work_experience> work_experience { get; set; }
    }
}
